from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.get_by_role("button", name="Login").click()
    page.get_by_label("Email").click()
    page.get_by_label("Email").fill("wsc-dev@gridos.com")
    page.get_by_label("Email").press("Tab")
    page.get_by_label("Password").fill("0pusOne")
    page.get_by_label("Password").press("Enter")
    page.locator("#react-select-2-input").press("ArrowDown")
    page.locator(".button").first.click()
    page.get_by_role("link", name="Create Program").click()
    page.get_by_placeholder("Name").click()
    page.get_by_placeholder("Name").fill("Automated Test")
    page.get_by_placeholder("Name").press("Tab")
    page.locator("#react-select-4-input").press("ArrowDown")
    page.locator(".css-x93v5g-control > .css-1ctqnuy > .css-ackcql").first.click()
    page.locator("#react-select-5-input").fill("toront")
    page.locator("#react-select-5-input").press("Enter")
    page.locator("#react-select-5-input").press("Tab")
    page.locator("#react-select-6-input").press("Tab")
    page.locator("#react-select-7-input").press("Tab")
    page.get_by_test_id("number-input").press("Tab")
    page.locator("#react-select-8-input").press("ArrowDown")
    page.locator("#react-select-8-input").press("ArrowDown")
    page.locator("#react-select-8-input").press("ArrowUp")
    page.locator("#react-select-8-input").press("ArrowUp")
    page.locator("#react-select-8-input").press("Tab")
    page.get_by_role("button", name="Pay as bid").click()
    page.get_by_role("button", name="Cost-Optimize Enrolled Assets").click()
    page.get_by_role("button", name="GridOS will automatically confirm events based on acceptance by users").click()
    page.get_by_role("button", name="User").nth(2).click()
    page.get_by_role("button", name="User").nth(2).click()
    page.get_by_role("button", name="Save").click()
    page.locator(".button").first.click()
    page.get_by_role("link", name="Admin Panel").click()
    page.get_by_role("link", name="Programs").click()
    page.locator(".button").first.click()
    page.get_by_role("link", name="Admin Panel").click()
    page.get_by_text("ProgramsService StatusSimulationsTrigger Events").click()
    page.get_by_role("link", name="Programs").click()
    page.locator(".button").first.click()
    page.get_by_role("link", name="Admin Panel").click()
    page.get_by_role("link", name="Trigger Events").click()
    page.locator(".button").first.click()
    page.get_by_role("link", name="Admin Panel").click()
    page.get_by_role("link", name="Admin Panel").press("Tab")
    page.get_by_role("link", name="User manual").press("Tab")
    page.get_by_role("link", name="Terms & Conditions").press("Tab")
    page.get_by_role("link", name="Report an issue").press("Tab")
    page.get_by_role("button", name="Logout").press("Tab")
    page.get_by_role("link", name="Programs").press("Enter")
